---
title: "RedSox2012_2017"
author: "Sky Liu"
date: "10/10/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
require(gdata)
```
## Load raw data

```{r load_Redsox_data include=FALSE}
#load RedSox Attendance Data from 2012 to 2017
RedSox2017 = read.xls ("Redsox_HT_1009.xlsx", sheet = 1, header = TRUE)
RedSox2016 = read.xls ("Redsox_HT_1009.xlsx", sheet = 2, header = TRUE)
RedSox2015 = read.xls ("Redsox_HT_1009.xlsx", sheet = 3, header = TRUE)
RedSox2014 = read.xls ("Redsox_HT_1009.xlsx", sheet = 4, header = TRUE)
RedSox2013 = read.xls ("Redsox_HT_1009.xlsx", sheet = 5, header = TRUE)
RedSox2012 = read.xls ("Redsox_HT_1009.xlsx", sheet = 6, header = TRUE)
```

```{r load_Basketball_data include=FALSE}
#load Basketball Attendance Data from 2012 to 2017
Basket2012 = read.xls ("BasketballData_1014.xlsx", sheet = 1, header = TRUE)
Basket2013 = read.xls ("BasketballData_1014.xlsx", sheet = 2, header = TRUE)
Basket2014 = read.xls ("BasketballData_1014.xlsx", sheet = 3, header = TRUE)
Basket2015 = read.xls ("BasketballData_1014.xlsx", sheet = 4, header = TRUE)
Basket2016 = read.xls ("BasketballData_1014.xlsx", sheet = 5, header = TRUE)
Basket2017 = read.xls ("BasketballData_1014.xlsx", sheet = 6, header = TRUE)
```

```{r load_Buoy_data include=FALSE}
#load buoy weather data from 2012 to 2017
buoy_data <- read_csv("buoydt.csv")
```

```{r load_Weather include=FALSE}
#load weather data from 
Weather <- read_csv("Weather.csv")
```


## merge data


```{r}
#Merge 6 year redsox data into one sheet
year <- rep.int(2012, 162)
year <- as.data.frame(year)
RedSox2012 <- cbind(year,RedSox2012)
year <- rep.int(2013, 162)
year <- as.data.frame(year)
RedSox2013 <- cbind(year,RedSox2013)
year <- rep.int(2014, 162)
year <- as.data.frame(year)
RedSox2014 <- cbind(year,RedSox2014)
year <- rep.int(2015, 162)
year <- as.data.frame(year)
RedSox2015 <- cbind(year,RedSox2015)
year <- rep.int(2016, 162)
year <- as.data.frame(year)
RedSox2016 <- cbind(year,RedSox2016)
year <- rep.int(2017, 162)
year <- as.data.frame(year)
RedSox2017 <- cbind(year,RedSox2017)
RedSox2012_2017 <- rbind(RedSox2012,RedSox2013,RedSox2014,RedSox2015,RedSox2016,RedSox2017)
```

```{r}
#Merge 6 year basketball data into one sheet
Basket2012_2017 <- rbind(Basket2012,Basket2013,Basket2014,Basket2015,Basket2016,Basket2017)
```

## Clean data

filter the data 'year', 'date', 'X2'(host or guest), ???W.L.1???(win or lost record)??? 'D/N' (Day/Night?), 'Attendance'

```{r}
#reformat the date as Day_of_Week, Month, DayofMonth
RedSox2012_2017 <- select(RedSox2012_2017,year,Date,X2,W.L.1,D.N,Attendance) %>% 
  separate(Date,c("Day_of_Week","Date"),",") %>% 
  separate(Date,c("A", "Month", "DayofMonth"),extra = "drop", fill = "right") 
RedSox2012_2017 <- dplyr::select(RedSox2012_2017,-A)
#reformat Month data from abbreviation to number
RedSox2012_2017$Month<- match(RedSox2012_2017$Month, month.abb)
#clean opponent information
RedSox2012_2017 <- dplyr::filter(RedSox2012_2017,X2 != '@') 
RedSox2012_2017 <- dplyr::select(RedSox2012_2017,-c(X2))

#Combine year/month/dayofmonth as one column
RedSox2012_2017 <- RedSox2012_2017 %>% mutate(Date = paste(year, Month, DayofMonth, sep = "-")) %>% select(Date, everything())
RedSox2012_2017 <- dplyr::select(RedSox2012_2017,-c(Month,DayofMonth))

#reformat win/lost record
colnames(RedSox2012_2017) <- c('Date','Year','Day_of_Week','WL','DN','Attendance')
RedSox2012_2017 <- RedSox2012_2017 %>% separate(WL,c("Win","Lost"),"-") %>% mutate(GameBehind = as.numeric(Lost) - as.numeric(Win))

```


```{r}
#reformat the date as Day_of_Week, Month, DayofMonth
Basket2012_2017 <- select(Basket2012_2017,YEAR,DATE,OPPONENT,W.L,ATTENDANCE) 
Basket2012_2017 <-  separate(Basket2012_2017,DATE,c("Day_of_Week","Date"),",") %>% 
  separate(Date,c("A", "Month", "DayofMonth"),extra = "drop", fill = "right") 
Basket2012_2017 <- dplyr::select(Basket2012_2017,-A)
#reformat Month data from abbreviation to number
Basket2012_2017$Month<- match(Basket2012_2017$Month, month.abb)
#clean opponent information
Basket2012_2017$OPPONENT <-  str_replace(Basket2012_2017$OPPONENT,"vs", "")
#Combine year/month/dayofmonth as one column
Basket2012_2017 <- mutate(Basket2012_2017,Date = paste(YEAR, Month, DayofMonth, sep = "-"))%>% select(Date, everything())
Basket2012_2017 <- dplyr::select(Basket2012_2017,-c(Month,DayofMonth))
#reformat win/lost record
colnames(Basket2012_2017) <- c('Date','Year','Day_of_Week','Opponent','WL','Attendance')
Basket2012_2017 <- Basket2012_2017 %>% separate(WL,c("Win","Lost"),"-") %>% mutate(GameBehind = as.numeric(Lost) - as.numeric(Win))
```

```{r}
#Combine year/month/dayofmonth as one column
buoy_data <- mutate(buoy_data,Date = paste(YYYY, MM, DD, sep = "-"))
buoy_data <- buoy_data %>% select(Date, everything())
buoy_data <- dplyr::select(buoy_data,-c(daily.record.time,YYYY, MM, DD))
```

```{r}
Weather <- Weather %>% select(DATE, PRCP,SNOW,TMAX,TMIN) %>% mutate(DATE = str_replace(DATE, "/", "-"))
colnames(Weather) <- c('Date','PRCP','Snow','Tmax','Tmin')
Weather <- Weather %>% mutate(Date = str_replace(Date, "/", "-"))
```



```{r}
# Join Buoy and Basketball
BuoyBasket <- inner_join(buoy_data, Basket2012_2017, by = c("Date" = "Date"))
## Join BuoyBasket and Weather
CelticsWeather <- inner_join(Weather, BuoyBasket, by = c("Date" = "Date"))
#delete outliers of ATMP
CelticsWeather <- CelticsWeather %>% group_by(ATMP) %>% arrange(ATMP) %>% filter(ATMP<=70)
write_csv(CelticsWeather, "CelticsWeather.csv")
```


```{r}
# Join Buoy and Redsox
BuoyRedsox <- inner_join(buoy_data, RedSox2012_2017, by = c("Date" = "Date"))
# Join BuoyRedsox and Weather
RedSoxWeather <- inner_join(Weather, BuoyRedsox, by = c("Date" = "Date"))
#delete outliers of ATMP
RedSoxWeather <- RedSoxWeather %>% group_by(ATMP) %>% arrange(ATMP) %>% filter(ATMP<=104)
write_csv(RedSoxWeather, "RedSoxWeather.csv")
```


###To use the prepared data, just use code below

```{r}
RedSoxWeather <- read_csv("RedSoxWeather")
CelticsWeather <- read_csv("CelticsWeather.csv")
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
